export const FixIdValues = [
	"replace-node-fs",
	"add-filter-or-fail-validator",
	"wrap-effect-map-callback",
	"replace-context-tag",
	"replace-promise-all",
	"replace-console-log",
	"add-schema-decode",
	// Original 17 anti-pattern fixes
	"add-concurrency-limit",
	"add-fiber-supervision",
	"replace-blocking-calls",
	"use-acquire-release",
	"fix-scope-leak",
	"replace-platform-imports",
	"add-effect-logging",
	"replace-any-with-types",
	"remove-non-null-assertions",
	"convert-default-to-named-exports",
	// Top 10 correctness anti-pattern fixes
	"replace-yield-with-yield-star",
	"replace-throw-with-effect-fail",
	"replace-async-callbacks-with-effect",
	"remove-or-die-outside-boundaries",
	"add-logging-to-catchall",
	"replace-effect-ignore",
	"replace-try-catch-with-effect-try",
	"replace-promise-apis-with-effect",
	"replace-generic-error-with-tagged",
	// Design smell fixes
	"refactor-switch-to-tagged-union",
	// Error modeling fixes
	"replace-error-with-tagged-type",
	"normalize-error-shapes",
	"preserve-error-structure",
	"wrap-error-with-context",
	"propagate-errors-upward",
	"model-expected-states-as-data",
	"use-effect-fail-for-domain-errors",
	"add-error-payload-fields",
	"narrow-unknown-error-type",
	"structure-error-propagation",
	// Domain modeling fixes
	"introduce-branded-types",
	"replace-boolean-with-tagged-union",
	"replace-magic-strings-with-union",
	"model-explicit-state-machine",
	"extract-domain-predicates",
	"use-domain-specific-errors",
	"structure-config-schema",
	"introduce-branded-ids",
	"use-duration-abstraction",
	"encode-domain-in-types",
	// Concurrency fixes
	"add-concurrency-limit-to-effect-all",
	"add-fiber-supervision-or-join",
	"replace-loop-fork-with-foreach",
	"handle-race-interruption",
	"offload-blocking-work",
	"replace-promise-all-with-effect-all",
	"observe-fiber-results",
	"add-retry-coordination",
	"use-ref-for-shared-state",
	"ensure-cancellation-awareness",
	// Scope fixes
	"wrap-with-acquire-release",
	"return-scoped-effect",
	"bind-scope-to-lifetime",
	"move-resource-to-app-layer",
	"convert-singleton-to-layer",
	"remove-manual-close",
	"scope-resources-before-run",
	"flatten-resource-acquisition",
	"use-explicit-scope",
	"add-layer-provision",
] as const;

export type FixId = (typeof FixIdValues)[number];

export const RuleIdValues = [
	"async-await",
	"node-fs",
	"missing-validation",
	"effect-map-fn-reference",
	"try-catch-in-effect",
	"try-catch-boundary-ok",
	"catch-log-and-swallow",
	"throw-in-effect-code",
	"any-type",
	"yield-star-non-effect",
	"non-typescript",
	"context-tag-anti-pattern",
	"promise-all-in-effect",
	"mutable-ref-in-effect",
	"console-log-in-effect",
	"effect-runSync-unsafe",
	"missing-error-channel",
	"layer-provide-anti-pattern",
	"effect-gen-no-yield",
	"schema-decode-unknown",
	// Original 17 anti-patterns
	"effect-run-promise-boundary",
	"throw-in-effect-pipeline",
	"swallow-failures-without-logging",
	"generic-error-type",
	"incorrect-promise-bridge",
	"fire-and-forget-fork",
	"unbounded-parallelism",
	"blocking-calls-in-effect",
	"manual-resource-lifecycle",
	"leaking-scopes",
	"node-platform-in-shared-code",
	"console-log-in-effect-flow",
	"any-type-usage",
	"unknown-without-narrowing",
	"non-null-assertions",
	"default-exports-in-core",
	"duplicate-pattern-ids",
	"unreachable-rule-declaration",
	"missing-rule-documentation",
	// Top 10 correctness anti-patterns
	"run-effect-outside-boundary",
	"yield-instead-of-yield-star",
	"throw-inside-effect-logic",
	"async-callbacks-in-effect-combinators",
	"or-die-outside-boundaries",
	"swallowing-errors-in-catchall",
	"effect-ignore-on-failable-effects",
	"try-catch-inside-effect-logic",
	"promise-apis-inside-effect-logic",
	"public-apis-returning-generic-error",
	// Design smell detectors
	"large-switch-statement",
	// Error modeling anti-patterns
	"error-as-public-type",
	"mixed-error-shapes",
	"convert-errors-to-strings-early",
	"catch-and-rethrow-generic",
	"catching-errors-too-early",
	"expected-states-as-errors",
	"exceptions-for-domain-errors",
	"error-tags-without-payloads",
	"overusing-unknown-error-channel",
	"logging-instead-of-modeling-errors",
	// Domain modeling anti-patterns
	"primitives-for-domain-concepts",
	"boolean-flags-controlling-behavior",
	"magic-string-domains",
	"objects-as-implicit-state-machines",
	"domain-logic-in-conditionals",
	"adhoc-error-semantics-in-domain",
	"overloaded-config-objects",
	"domain-ids-as-raw-strings",
	"time-as-number-or-date",
	"domain-meaning-from-file-structure",
	// Concurrency anti-patterns
	"unbounded-parallelism-effect-all",
	"fire-and-forget-forks",
	"forking-inside-loops",
	"racing-without-handling-losers",
	"blocking-calls-in-effect-logic",
	"promise-concurrency-in-effect",
	"ignoring-fiber-failures",
	"retrying-concurrently-without-limits",
	"shared-mutable-state-across-fibers",
	"timeouts-without-cancellation-awareness",
	// Scope anti-patterns
	"resources-without-acquire-release",
	"returning-resources-instead-of-effects",
	"creating-scopes-without-binding",
	"long-lived-resources-in-short-scopes",
	"global-singletons-instead-of-layers",
	"closing-resources-manually",
	"effect-run-with-open-resources",
	"nested-resource-acquisition",
	"using-scope-global-for-convenience",
	"forgetting-to-provide-layers",
] as const;

export type RuleId = (typeof RuleIdValues)[number];
