# .github/workflows/generate-docs.yml

# 1. The name of the workflow, which will appear in the GitHub Actions UI.
name: Generate Docs & Rules

# 2. The trigger: This workflow runs on every `push` to the `main` branch.
on:
  push:
    branches:
      - main

# 3. The list of jobs to run. We only have one job.
jobs:
  generate:
    # 4. The name of the job.
    name: Generate README and Rules
    # 5. The virtual machine to run on. 'ubuntu-latest' is standard and cost-effective.
    runs-on: ubuntu-latest

    # 6. The sequence of steps the job will perform.
    steps:
      # Step 6a: Checks out your repository's code onto the virtual machine.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 6b: Sets up Bun runtime.
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Step 6c: Installs the project dependencies.
      - name: Install Dependencies
        run: bun install

      # Step 6d: Runs your README generation script.
      - name: Generate README
        run: bun run generate

      # Step 6e: Runs your rules generation script.
      - name: Generate Rules
        run: bun run rules

      # Step 6g: This is the magic step. It checks if any files have changed.
      # If they have, it automatically commits and pushes them back to your repo.
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # The message for the automatic commit.
          commit_message: "docs: auto-generate README and rules"
          # Only commit changes to these specific files.
          file_pattern: "README.md rules/*"